title: RP Strength Documentation
description: Documentation for RP Strength Apps
remote_theme: just-the-docs/just-the-docs

url: https://docs.rpstrength.com/docs/

aux_links:
  Diet Coach App Home: https://rpstrength.com/pages/diet-coach-app
  Hypertrophy App Home: https://rpstrength.com/pages/hypertrophy-app


aux_links_new_tab: true

logo: "/assets/images/logo-docs-big@2x.png"

back_to_top: true
back_to_top_text: "Back to top"

color_scheme: rpdark

callouts:
  note:
    title: Note
    color: blue-energetic

collections:
  diet:
    output: true
    permalink: "/docs/diet-coach-app/:path/"
  hypertrophy:
    output: true
    permalink: "/docs/hypertrophy-app/:path/"

just_the_docs:
  collections:
    diet:
      name: Diet Coach App
    hypertrophy:
      name: Hypertrophy App

defaults:
  -
    scope:
      path: "docs/**/index.md"
    values:
      layout: "default"
      permalink: "/:path/"
  -
    scope:
      path: "docs"
    values:
      layout: "default"
      permalink: "/:path/:basename/"
  -
    scope:
      path: "_diet"
    values:
      layout: "default"